"""Relationship many to many products - inconterms

Revision ID: 80484b4fc716
Revises: 7bd9bc574dc3
Create Date: 2022-11-02 11:40:28.334816

"""
from alembic import op
import sqlalchemy as sa
# Import to no generate error in migrations
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '80484b4fc716'
down_revision = '7bd9bc574dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_incoterms',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('incoterm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'incoterm_id')
    )
    op.drop_constraint('products_incoterm_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'incoterm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('incoterm_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_incoterm_id_fkey', 'products', 'incoterms', ['incoterm_id'], ['id'])
    op.drop_table('product_incoterms')
    # ### end Alembic commands ###
