"""init-db

Revision ID: b1d69a7183d9
Revises: 
Create Date: 2022-10-22 16:40:42.096694

"""
from alembic import op
import sqlalchemy as sa
# Import to no generate error in migrations
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b1d69a7183d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='db-test-bazar-offchain'
    )
    op.create_table('profile_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('image_name', sa.String(length=250), nullable=True),
    sa.Column('format', sa.String(length=250), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='db-test-bazar-offchain'
    )
    op.create_table('status_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('status_user', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_user'),
    sa.UniqueConstraint('uuid'),
    schema='db-test-bazar-offchain'
    )
    op.create_table('status_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('status_user', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_user'),
    sa.UniqueConstraint('uuid'),
    schema='db-test-bazar-offchain'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('rol', sa.String(length=250), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['db-test-bazar-offchain.status_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='db-test-bazar-offchain'
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('chamber_commerce', sa.String(length=20), nullable=True),
    sa.Column('legal_representative', sa.String(length=250), nullable=True),
    sa.Column('operative_years', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_image_id'], ['db-test-bazar-offchain.profile_images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db-test-bazar-offchain.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='db-test-bazar-offchain'
    )
    op.create_table('files_company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('status_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['db-test-bazar-offchain.companies.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['db-test-bazar-offchain.files.id'], ),
    sa.ForeignKeyConstraint(['status_file_id'], ['db-test-bazar-offchain.status_file.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'file_id'),
    schema='db-test-bazar-offchain'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_company', schema='db-test-bazar-offchain')
    op.drop_table('companies', schema='db-test-bazar-offchain')
    op.drop_table('users', schema='db-test-bazar-offchain')
    op.drop_table('status_user', schema='db-test-bazar-offchain')
    op.drop_table('status_file', schema='db-test-bazar-offchain')
    op.drop_table('profile_images', schema='db-test-bazar-offchain')
    op.drop_table('files', schema='db-test-bazar-offchain')
    # ### end Alembic commands ###
